### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ehouarn-perret** [TheAngryByrd/Marten.FSharp#28]
Just wondering out of curiosity if this project is still maintained?

**Comment by TheAngryByrd** [comment]
Yup! Since it's a thin wrapper it doesnt need updated often. If something is broke open an issue! 😊

**Comment by ehouarn-perret** [comment]
@TheAngryByrd thanks ^^", will let you know if I ever find something suspicious ;-)

**Comment by jannikbuschke** [comment]
@TheAngryByrd if this is still maintained, does it make sense to release a v1?
When quickly checking this repo I also got the feelign it is unmaintaned..
