### ISSUE TITLE
A more functional way of including related documents

### ISSUE THREAD

**Issue by sheridanchris** [TheAngryByrd/Marten.FSharp#31]
As you can see [here](https://martendb.io/documents/querying/linq/include.html#including-related-documents) including related documents requires a separate mutable binding.

I wonder if there's a way to accomplish the same effect while giving the consumer a tuple value of `'entity * 'included`
(or something similar)

**Comment by sheridanchris** [comment]
Maybe something like this?
```fsharp
let includeSingle<'entity, 'included> (selector: Quotations.Expr<'entity -> obj>) (q: IQueryable<'entity>) =
    let mutable single: 'included option = None
    q.Include(selector |> Lambda.ofArity1, fun x -> single <- Some x)
    // do something here?
```

**Comment by TheAngryByrd** [comment]
I think that's fine.  However you do have to force the query to start somehow (their example uses `.Single()` or this probably wont work.  

If this is required for strictly building our a query pipeline, maybe [`TaskCompletionSource` ](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=net-6.0)and `TrySetResult` make sense here?

**Comment by sheridanchris** [comment]
My original idea was after you call `includeSingle` you would call `q.Single` yourself with a predicate.
Although my code snippet above wouldn't work well in a pipeline.
I'll have to think about it some more, thanks for the feedback.
