### ISSUE TITLE
Migrate quotations to anonymous functions

### ISSUE THREAD

**Issue by sheridanchris** [TheAngryByrd/Marten.FSharp#32]
There are some instances where expressions are required and quotations + `Lambda.ofArity1` could be of use... especially considering the nuances of calling C# overloads in F#.

Here's a practical example
```fs
options
    .Schema
    .For<Post>()
    .FullTextIndex(ofArity1 <@ fun post -> box post.Headline @>)
```

This compiles while the equivalent anonymous function: `fun post -> ...` does not.

**Comment by TheAngryByrd** [comment]
I now wonder if quotations is actually the correct approach now.  When I started this, F# didn't have the same easy of use to deal with F# Lambdas -> Func/Action calls as they seem to today.

**Comment by sheridanchris** [comment]
Hmmm, you're right. I haven't gotten all of the StoreOptions configuration code to work with _just lambdas_, but it's definitely doable. I can migration everything from quotations to lambdas if you'd like.

**Comment by TheAngryByrd** [comment]
>  I haven't gotten all of the StoreOptions configuration code to work with just lambdas

Definitely explore this more as those are the type of helpers we need to have.

**Comment by sheridanchris** [comment]
The main limiting factor, it seems, is working with expressions arrays.
I'm not entirely sure how to interop here.
![](https://i.imgur.com/JXU5q7E.png)

**Comment by TheAngryByrd** [comment]
hmm... does having type annotations help in this case? like `(fun (post : Post) -> box post.Headline)`

**Comment by sheridanchris** [comment]
It does not. I also tried with explicit parameter names (type inference was wrong).
It doesn't want to convert the lambda to an expression in this case.

**Comment by sheridanchris** [comment]
Found a little workaround... I'll work on improving it.
```fs
let exp (f: Post -> obj) : Expression<Func<Post, obj>> = f
```

**Comment by sheridanchris** [comment]
Afaik anonymous functions alone won't work as they don't have a `members` value (on the expression). Some expression magic is needed as I'm not entirely sure implicit conversions will do the trick.

**Comment by TheAngryByrd** [comment]
Ok makes sense! Let’s expose those lambda arity helpers.
