### ISSUE TITLE
Add more pipeline opportunities 

### ISSUE THREAD

**Issue by sheridanchris** [TheAngryByrd/Marten.FSharp#33]
Find areas in the codebase to add pipeline opportunities.

For example:
session functions like deleteX and storeX return unit. Instead, they should _probably_ return the session.

Before:
```fs
let storeUserAsync (user: User) (documentSession: IDocumentSession) =
    documentSession |> Session.storeSingle user
    documentSession |> Session.saveChangesAsync
```

After:
```fs
let storeUserAsync (user: User) (documentSession: IDocumentSession) =
    documentSession
    |> Session.storeSingle user
    |> Session.saveChangesAsync
```

The only downside is, this will cause warnings as existing code will be ignoring the return values.
Also, in some instances you'd want to ignore the return value, for various reasons... maybe separate functions can be used???
I'm not sure.

**Comment by TheAngryByrd** [comment]
I'd lean toward whatever the underlying return type is and not try to be fancy with it. Deviating too much might provide a cognitive overhead when reading the actual Marten docs.
