### ISSUE TITLE
Query builder

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/Marten.FSharp#40]
It would be interesting to see if we could create a [custom query builder](https://tomasp.net/blog/2015/query-translation/index.html) for Marten style queries.

**Comment by sheridanchris** [comment]
This is supported out-of-the-box as Marten uses IQueryable's

Example:
```fs
let dog =
    query {
        for dog in Session.query<Dog> session do
            where (dog.Name = "Spark" && dog.FavoriteChewToy = "Macbook")
            head
    }
```

**Comment by TheAngryByrd** [comment]
Wooo
