### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/Marten.FSharp#7]
I'm thinking of how to go about the design of the API for this. 

Right now I've just stuck everything under the `Doc` module.  I'm thinking we should break it up a little bit more.

I've done an initial refactor https://github.com/TheAngryByrd/Marten.FSharp/blob/api-redesign/src/Marten.FSharp/Marten.FSharp.fs

@ibnuda any input?

**Comment by ibnuda** [comment]
Looks great! Though personally, I still don't get when I have to use `IQuerySession` and `IDocumentSession`. Perhaps those two can be separated like in [Marten's doc.](http://jasperfx.github.io/marten/documentation/documents/)
```
// query, read, write, etc.
let query<'a> (session : IDocumentSession) =
    session.Query<'a>()
// just query without write.
let query<'a> (session : IQuerySession) =
    session.Query<'a>()
```

**Comment by TheAngryByrd** [comment]
I've never used `IQuerySession` before.  I guess it's for scenarios which you don't want to accidentally save things.  I guess since [IDocumentSession 
 inherits from IQuerySession](https://github.com/JasperFx/marten/blob/master/src/Marten/IDocumentSession.cs) we can just change the `query` function to `#IQuerySession` and won't matter if you pass in either.

**Comment by TheAngryByrd** [comment]
Ok I just changed all the read functions like `query` and `load` to `IQuerySession` https://github.com/TheAngryByrd/Marten.FSharp/commit/baa78c424a7ee859b9feffc69f66ff1dcf9cc045

**Comment by TheAngryByrd** [comment]
Also should I move all the `IDocumentSession` parameters to be first or last?

```FSharp
session
|> loadByIntAsync<Person> 42
```

or

```FSharp
42
|> loadByIntAsync<Person> session
```

**Comment by ibnuda** [comment]
Really nice!
And yes, I also use this library (in my [toy project](https://gitlab.com/ibnuda/Forum/blob/master/src/Libr/Db/MartenFSharp.fs)) `IDocumentSession` as the last parameters.

**Comment by TheAngryByrd** [comment]
Ok moved to last param in https://github.com/TheAngryByrd/Marten.FSharp/commit/50754fc0d11e598b3bde7aa02579bf32cd6a96c7
